### ISSUE TITLE
[BUG] Cannot join server

### ISSUE THREAD

**Issue by RandomisedTV** [Alujjdnd/Ngrok-LAN#10]
**Describe the bug**
Cannot join a friend's server.

**Desktop:**
 - OS: Windows 10
 - Minecraft Version 1.18.2
 - Ngrok-LAN Version 1.4.0

**Additional context**
Tried to join a friend's server, got "Connection refused: no further information". Others had managed to connect but for some reason I couldn't.

Error log:

> [03:56:02] [Render thread/INFO]: Connecting to 6.tcp.ngrok.io, 16435
[03:56:04] [Server Connector #1/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: 6.tcp.ngrok.io/62.24.138.17:16435
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:56:25] [Render thread/INFO]: Stopping!

**Comment by Flooflez** [comment]
Thank you for the bug report, but this is likely not an issue with our mod.

Only the host needs to install the mod, and the server connection from the clients is the same as a regular vanilla server connection. It's unlikely that our mod is causing the issue.

We would still like to help resolve the issue, but to fully understand what is going on it would be useful to test these things first:
- Obtain the minecraft logs from the server host to see why you cannot connect.
- Have another friend host an Ngrok LAN world and connect to their world.
- Used a cracked version of Minecraft or another account to connect.
- Join the server by yourself (no other connected clients) as you may be reaching Ngrok's free account connection limit.

If you still cannot connect to any Ngrok LAN worlds, please let us know.
I will close this issue for now, but feel free to reopen it if you deem necessary.
